export const tools = [
  {
    id: "merge",
    name: "Unisci PDF",
    category: "Organizza",
    badge: "Popolari",
    icon: "U",
    status: "attivo",
    minFiles: 2,
    accepts: ["pdf"],
    description: "Combina più PDF in un solo documento.",
  },
  {
    id: "merge-mixed",
    name: "Unisci PDF+immagini",
    category: "Organizza",
    badge: "Nuovo",
    icon: "MI",
    status: "attivo",
    minFiles: 2,
    accepts: ["pdf", "jpg", "jpeg", "png"],
    description: "Combina PDF, JPG e PNG in un unico documento seguendo l'ordine della coda.",
  },
  {
    id: "interleave",
    name: "Intercala PDF",
    category: "Organizza",
    badge: "Attivo",
    icon: "I",
    status: "attivo",
    minFiles: 2,
    maxFiles: 2,
    accepts: ["pdf"],
    description: "Alterna due PDF, utile per scansioni fronte/retro separate.",
    options: [
      {
        id: "secondOrder",
        label: "Secondo PDF",
        type: "select",
        value: "reverse",
        choices: [
          ["reverse", "Inverti ordine"],
          ["normal", "Mantieni ordine"],
        ],
      },
    ],
  },
  {
    id: "split",
    name: "Dividi PDF",
    category: "Organizza",
    badge: "Popolari",
    icon: "D",
    status: "attivo",
    accepts: ["pdf"],
    description: "Crea uno ZIP con un PDF per ogni pagina.",
  },
  {
    id: "split-ranges",
    name: "Dividi per range",
    category: "Organizza",
    badge: "Attivo",
    icon: "R",
    status: "attivo",
    accepts: ["pdf"],
    description: "Crea uno ZIP con un PDF per ogni blocco di pagine.",
    options: [
      {
        id: "ranges",
        label: "Blocchi",
        type: "text",
        value: "1-3;4-6;last",
        hint: "Separa i blocchi con ; esempio: 1-3;4-6;last",
      },
    ],
  },
  {
    id: "split-odd-even",
    name: "Separa pari/dispari",
    category: "Organizza",
    badge: "Attivo",
    icon: "P",
    status: "attivo",
    accepts: ["pdf"],
    description: "Crea PDF separati con pagine dispari e pari dentro uno ZIP.",
  },
  {
    id: "extract-pages",
    name: "Estrai pagine",
    category: "Organizza",
    badge: "Attivo",
    icon: "E",
    status: "attivo",
    accepts: ["pdf"],
    description: "Esporta solo le pagine indicate.",
    options: [
      { id: "ranges", label: "Pagine", type: "text", value: "1-3", hint: "Esempio: 1-3,5,last" },
    ],
  },
  {
    id: "remove-pages",
    name: "Rimuovi pagine",
    category: "Organizza",
    badge: "Attivo",
    icon: "R",
    status: "attivo",
    accepts: ["pdf"],
    description: "Elimina pagine o intervalli da un PDF.",
    options: [{ id: "ranges", label: "Pagine da rimuovere", type: "text", value: "1", hint: "Esempio: 1,4-6" }],
  },
  {
    id: "reorder-pages",
    name: "Riordina pagine",
    category: "Organizza",
    badge: "Attivo",
    icon: "O",
    status: "attivo",
    accepts: ["pdf"],
    description: "Ricostruisce il PDF con un nuovo ordine pagine.",
    options: [{ id: "order", label: "Nuovo ordine", type: "text", value: "last,1-2", hint: "Esempio: 3,1,2 oppure last,1-4" }],
  },
  {
    id: "rotate",
    name: "Ruota PDF",
    category: "Organizza",
    badge: "Popolari",
    icon: "↻",
    status: "attivo",
    accepts: ["pdf"],
    description: "Ruota tutte le pagine di 90, 180 o 270 gradi.",
    options: [
      {
        id: "angle",
        label: "Rotazione",
        type: "select",
        value: "90",
        choices: [
          ["90", "90°"],
          ["180", "180°"],
          ["270", "270°"],
        ],
      },
    ],
  },
  {
    id: "reverse-pages",
    name: "Inverti pagine",
    category: "Organizza",
    badge: "Attivo",
    icon: "I",
    status: "attivo",
    accepts: ["pdf"],
    description: "Crea una copia con ordine pagine invertito.",
  },
  {
    id: "duplicate-pages",
    name: "Duplica pagine",
    category: "Organizza",
    badge: "Attivo",
    icon: "2",
    status: "attivo",
    accepts: ["pdf"],
    description: "Duplica pagine o intervalli e li aggiunge in fondo al documento.",
    options: [{ id: "ranges", label: "Pagine da duplicare", type: "text", value: "1", hint: "Esempio: 1,3-5,last" }],
  },
  {
    id: "optimize",
    name: "Ottimizza leggero",
    category: "Ottimizza",
    badge: "Attivo",
    icon: "C",
    status: "attivo",
    accepts: ["pdf"],
    description: "Riscrive il PDF con object streams. Non comprime immagini già pesanti.",
  },
  {
    id: "compress-scan",
    name: "Comprimi scansione",
    category: "Ottimizza",
    badge: "Attivo",
    icon: "J",
    status: "attivo",
    accepts: ["pdf"],
    description: "Ricrea PDF scansionati in JPEG locale. Ideale per allegati immagine.",
    options: [
      {
        id: "quality",
        label: "Compressione",
        type: "select",
        value: "0.72",
        choices: [
          ["0.55", "Piccola"],
          ["0.72", "Bilanciata"],
          ["0.86", "Alta qualità"],
        ],
      },
      {
        id: "scale",
        label: "Definizione",
        type: "select",
        value: "1.1",
        choices: [
          ["0.9", "Leggera"],
          ["1.1", "Standard"],
          ["1.35", "Nitida"],
        ],
      },
    ],
  },
  {
    id: "enhance-scan",
    name: "Migliora scansione",
    category: "Ottimizza",
    badge: "Attivo",
    icon: "M",
    status: "attivo",
    accepts: ["pdf"],
    description: "Aumenta contrasto o crea bianco/nero netto, tutto nel browser.",
    options: [
      {
        id: "mode",
        label: "Modalità",
        type: "select",
        value: "contrast",
        choices: [
          ["contrast", "Contrasto"],
          ["bw", "Bianco e nero"],
        ],
      },
      {
        id: "scale",
        label: "Qualità",
        type: "select",
        value: "1.25",
        choices: [
          ["1", "Standard"],
          ["1.25", "Alta"],
          ["1.5", "Massima"],
        ],
      },
    ],
  },
  {
    id: "repair",
    name: "Ripara PDF",
    category: "Ottimizza",
    badge: "Roadmap",
    icon: "R",
    status: "bloccato",
    accepts: ["pdf"],
    description: "Richiede motori server tipo qpdf/ghostscript. Non attivo per evitare costi.",
  },
  {
    id: "images-to-pdf",
    name: "JPG/PNG in PDF",
    category: "Converti",
    badge: "Popolari",
    icon: "J",
    status: "attivo",
    accepts: ["jpg", "jpeg", "png"],
    description: "Crea un PDF da immagini locali.",
  },
  {
    id: "text-to-pdf",
    name: "TXT in PDF",
    category: "Converti",
    badge: "Attivo",
    icon: "T",
    status: "attivo",
    accepts: ["txt"],
    description: "Converte file di testo in PDF multipagina.",
  },
  {
    id: "blank-pdf",
    name: "Crea PDF vuoto",
    category: "Converti",
    badge: "Attivo",
    icon: "+",
    status: "attivo",
    minFiles: 0,
    description: "Genera un PDF vuoto, a righe o a griglia senza caricare file.",
    options: [
      { id: "pages", label: "Pagine", type: "text", value: "1", hint: "Numero pagine" },
      {
        id: "style",
        label: "Stile",
        type: "select",
        value: "blank",
        choices: [
          ["blank", "Vuoto"],
          ["lined", "A righe"],
          ["grid", "Griglia"],
        ],
      },
      {
        id: "pageSize",
        label: "Formato",
        type: "select",
        value: "a4-portrait",
        choices: [
          ["a4-portrait", "A4 verticale"],
          ["a4-landscape", "A4 orizzontale"],
          ["letter-portrait", "Letter verticale"],
          ["letter-landscape", "Letter orizzontale"],
        ],
      },
    ],
  },
  {
    id: "extract-text",
    name: "PDF in testo",
    category: "Converti",
    badge: "Popolari",
    icon: "X",
    status: "attivo",
    accepts: ["pdf"],
    description: "Estrae testo selezionabile in file TXT.",
  },
  {
    id: "pdf-to-markdown",
    name: "PDF in Markdown",
    category: "Converti",
    badge: "Nuovo",
    icon: "MD",
    status: "attivo",
    accepts: ["pdf"],
    description: "Converte il testo selezionabile in file Markdown con separatori pagina.",
  },
  {
    id: "pdf-to-word",
    name: "Word testo",
    category: "Converti",
    badge: "Testo",
    icon: "W",
    status: "attivo",
    accepts: ["pdf"],
    description: "Crea un DOCX editabile dal testo selezionabile. Non ricrea layout complessi o scansioni.",
  },
  {
    id: "pdf-to-images",
    name: "PDF in PNG",
    category: "Converti",
    badge: "Attivo",
    icon: "P",
    status: "attivo",
    accepts: ["pdf"],
    description: "Renderizza le pagine in immagini PNG dentro uno ZIP.",
    options: [
      {
        id: "scale",
        label: "Qualità",
        type: "select",
        value: "1.5",
        choices: [
          ["1", "Standard"],
          ["1.5", "Alta"],
          ["2", "Massima"],
        ],
      },
    ],
  },
  {
    id: "pdf-to-jpg",
    name: "PDF in JPG",
    category: "Converti",
    badge: "Attivo",
    icon: "J",
    status: "attivo",
    accepts: ["pdf"],
    description: "Renderizza pagine in JPG più leggeri dentro uno ZIP locale.",
    options: [
      {
        id: "quality",
        label: "Compressione",
        type: "select",
        value: "0.82",
        choices: [
          ["0.65", "Piccola"],
          ["0.82", "Bilanciata"],
          ["0.94", "Alta qualità"],
        ],
      },
      {
        id: "scale",
        label: "Qualità",
        type: "select",
        value: "1.5",
        choices: [
          ["1", "Standard"],
          ["1.5", "Alta"],
          ["2", "Massima"],
        ],
      },
    ],
  },
  {
    id: "pdf-to-webp",
    name: "PDF in WebP",
    category: "Converti",
    badge: "Attivo",
    icon: "W",
    status: "attivo",
    accepts: ["pdf"],
    description: "Renderizza le pagine in WebP leggero dentro uno ZIP locale.",
    options: [
      {
        id: "quality",
        label: "Compressione",
        type: "select",
        value: "0.8",
        choices: [
          ["0.6", "Piccola"],
          ["0.8", "Bilanciata"],
          ["0.92", "Alta qualità"],
        ],
      },
      {
        id: "scale",
        label: "Qualità",
        type: "select",
        value: "1.5",
        choices: [
          ["1", "Standard"],
          ["1.5", "Alta"],
          ["2", "Massima"],
        ],
      },
    ],
  },
  {
    id: "pdf-to-social",
    name: "PDF in social",
    category: "Converti",
    badge: "Nuovo",
    icon: "S",
    status: "attivo",
    accepts: ["pdf"],
    description: "Esporta ogni pagina come JPG già centrato per post, story o anteprime social.",
    options: [
      {
        id: "preset",
        label: "Formato",
        type: "select",
        value: "square",
        choices: [
          ["square", "Post quadrato"],
          ["story", "Story verticale"],
          ["link", "Anteprima link"],
        ],
      },
      {
        id: "background",
        label: "Sfondo",
        type: "select",
        value: "warm",
        choices: [
          ["warm", "Carta calda"],
          ["white", "Bianco"],
          ["dark", "Scuro"],
        ],
      },
    ],
  },
  {
    id: "pdf-to-long-jpg",
    name: "PDF in JPG lungo",
    category: "Converti",
    badge: "Attivo",
    icon: "L",
    status: "attivo",
    accepts: ["pdf"],
    description: "Unisce tutte le pagine in una singola immagine JPG verticale.",
    options: [
      {
        id: "quality",
        label: "Compressione",
        type: "select",
        value: "0.82",
        choices: [
          ["0.65", "Piccola"],
          ["0.82", "Bilanciata"],
          ["0.94", "Alta qualità"],
        ],
      },
      {
        id: "scale",
        label: "Qualità",
        type: "select",
        value: "1",
        choices: [
          ["0.75", "Leggera"],
          ["1", "Standard"],
          ["1.5", "Alta"],
        ],
      },
    ],
  },
  {
    id: "contact-sheet",
    name: "Scheda anteprime",
    category: "Converti",
    badge: "Attivo",
    icon: "M",
    status: "attivo",
    accepts: ["pdf"],
    description: "Crea un PDF A4 con miniature numerate delle pagine.",
    options: [
      {
        id: "columns",
        label: "Colonne",
        type: "select",
        value: "3",
        choices: [
          ["2", "2 colonne"],
          ["3", "3 colonne"],
        ],
      },
    ],
  },
  {
    id: "office-to-pdf",
    name: "Office in PDF",
    category: "Converti",
    badge: "Bloccato",
    icon: "O",
    status: "bloccato",
    description: "DOCX/PPTX/XLSX affidabili richiedono LibreOffice server o API paid.",
  },
  {
    id: "watermark",
    name: "Filigrana",
    category: "Modifica",
    badge: "Popolari",
    icon: "F",
    status: "attivo",
    accepts: ["pdf"],
    description: "Applica una filigrana testuale su tutte le pagine.",
    options: [{ id: "text", label: "Testo", type: "text", value: "PdfDelta", hint: "Testo filigrana" }],
  },
  {
    id: "image-stamp",
    name: "Logo/immagine",
    category: "Modifica",
    badge: "Attivo",
    icon: "IMG",
    status: "attivo",
    minFiles: 2,
    accepts: ["pdf", "jpg", "jpeg", "png"],
    description: "Applica il primo JPG/PNG caricato su ogni pagina PDF.",
    options: [
      {
        id: "position",
        label: "Posizione",
        type: "select",
        value: "top-right",
        choices: [
          ["top-right", "Alto destra"],
          ["top-left", "Alto sinistra"],
          ["bottom-right", "Basso destra"],
          ["bottom-left", "Basso sinistra"],
          ["center", "Centro"],
        ],
      },
      {
        id: "size",
        label: "Dimensione",
        type: "select",
        value: "0.16",
        choices: [
          ["0.10", "Piccola"],
          ["0.16", "Media"],
          ["0.24", "Grande"],
        ],
      },
    ],
  },
  {
    id: "page-numbers",
    name: "Numeri pagina",
    category: "Modifica",
    badge: "Attivo",
    icon: "#",
    status: "attivo",
    accepts: ["pdf"],
    description: "Aggiunge numerazione in basso a destra.",
  },
  {
    id: "edit-pdf",
    name: "Compila e firma",
    category: "Modifica",
    badge: "Editor",
    icon: "ED",
    status: "attivo",
    accepts: ["pdf"],
    description: "Editor visuale locale per compilare campi, aggiungere testo, firma e disegno.",
  },
  {
    id: "stamp-filename",
    name: "Timbra nome file",
    category: "Modifica",
    badge: "Nuovo",
    icon: "NF",
    status: "attivo",
    accepts: ["pdf"],
    description: "Scrive il nome del file su ogni pagina per archivi, revisioni e fascicoli.",
    options: [
      {
        id: "position",
        label: "Posizione",
        type: "select",
        value: "bottom-left",
        choices: [
          ["bottom-left", "Basso sinistra"],
          ["bottom-right", "Basso destra"],
          ["top-left", "Alto sinistra"],
          ["top-right", "Alto destra"],
        ],
      },
    ],
  },
  {
    id: "cover-page",
    name: "Copertina PDF",
    category: "Modifica",
    badge: "Attivo",
    icon: "CP",
    status: "attivo",
    accepts: ["pdf"],
    description: "Inserisce una copertina A4 con titolo, sottotitolo e data.",
    options: [
      { id: "title", label: "Titolo", type: "text", value: "Documento PdfDelta", hint: "Titolo copertina" },
      { id: "subtitle", label: "Sottotitolo", type: "text", value: "Generato localmente", hint: "Sottotitolo" },
    ],
  },
  {
    id: "header-footer",
    name: "Header/Footer",
    category: "Modifica",
    badge: "Attivo",
    icon: "H",
    status: "attivo",
    accepts: ["pdf"],
    description: "Aggiunge intestazione e piè pagina testuali a tutte le pagine.",
    options: [
      { id: "header", label: "Intestazione", type: "text", value: "PdfDelta", hint: "Testo in alto" },
      { id: "footer", label: "Piè pagina", type: "text", value: "Documento gratuito", hint: "Testo in basso" },
    ],
  },
  {
    id: "letterhead",
    name: "Carta intestata",
    category: "Modifica",
    badge: "Attivo",
    icon: "L",
    status: "attivo",
    minFiles: 2,
    maxFiles: 2,
    accepts: ["pdf"],
    description: "Applica il primo foglio del secondo PDF come template su tutte le pagine.",
    options: [
      {
        id: "layer",
        label: "Livello",
        type: "select",
        value: "background",
        choices: [
          ["background", "Sfondo"],
          ["foreground", "Sopra"],
        ],
      },
    ],
  },
  {
    id: "bates",
    name: "Bates numbering",
    category: "Modifica",
    badge: "Attivo",
    icon: "B",
    status: "attivo",
    accepts: ["pdf"],
    description: "Aggiunge numerazione progressiva per fascicoli legali o archivi.",
    options: [
      { id: "prefix", label: "Prefisso", type: "text", value: "PD-", hint: "Esempio: CASE-" },
      { id: "start", label: "Numero iniziale", type: "text", value: "1", hint: "Esempio: 1001" },
    ],
  },
  {
    id: "sign-text",
    name: "Firma testuale",
    category: "Modifica",
    badge: "Attivo",
    icon: "S",
    status: "attivo",
    accepts: ["pdf"],
    description: "Inserisce una firma testuale sull'ultima pagina.",
    options: [{ id: "signature", label: "Firma", type: "text", value: "Firmato digitalmente", hint: "Nome o testo firma" }],
  },
  {
    id: "nup",
    name: "N-up stampa",
    category: "Modifica",
    badge: "Attivo",
    icon: "N",
    status: "attivo",
    accepts: ["pdf"],
    description: "Impagina 2 o 4 pagine su ogni foglio.",
    options: [
      {
        id: "layout",
        label: "Layout",
        type: "select",
        value: "2",
        choices: [
          ["2", "2 pagine per foglio"],
          ["4", "4 pagine per foglio"],
        ],
      },
    ],
  },
  {
    id: "booklet",
    name: "Booklet stampa",
    category: "Modifica",
    badge: "Attivo",
    icon: "BK",
    status: "attivo",
    accepts: ["pdf"],
    description: "Impone le pagine in formato libretto fronte/retro, pronto per stampa.",
  },
  {
    id: "poster-tiles",
    name: "Poster multipagina",
    category: "Modifica",
    badge: "Nuovo",
    icon: "PT",
    status: "attivo",
    accepts: ["pdf"],
    description: "Ingrandisce ogni pagina e la divide su più fogli stampabili.",
    options: [
      {
        id: "grid",
        label: "Griglia",
        type: "select",
        value: "2x2",
        choices: [
          ["2x2", "2 x 2"],
          ["3x3", "3 x 3"],
          ["2x3", "2 x 3"],
        ],
      },
    ],
  },
  {
    id: "qr-on-pdf",
    name: "QR su PDF",
    category: "Modifica",
    badge: "Attivo",
    icon: "Q",
    status: "attivo",
    accepts: ["pdf"],
    description: "Inserisce un QR code nell'angolo basso della prima pagina.",
    options: [
      { id: "text", label: "Contenuto QR", type: "text", value: "https://pdfdelta.pages.dev", hint: "URL o testo" },
      {
        id: "position",
        label: "Posizione",
        type: "select",
        value: "bottom-right",
        choices: [
          ["bottom-right", "Basso destra"],
          ["bottom-left", "Basso sinistra"],
          ["top-right", "Alto destra"],
          ["top-left", "Alto sinistra"],
        ],
      },
    ],
  },
  {
    id: "add-margins",
    name: "Aggiungi margini",
    category: "Modifica",
    badge: "Attivo",
    icon: "A",
    status: "attivo",
    accepts: ["pdf"],
    description: "Reimpagina ogni pagina su A4 con margine uniforme.",
    options: [
      {
        id: "margin",
        label: "Margine",
        type: "select",
        value: "36",
        choices: [
          ["24", "Piccolo"],
          ["36", "Medio"],
          ["54", "Grande"],
        ],
      },
    ],
  },
  {
    id: "print-safe-scale",
    name: "Margine stampabile",
    category: "Modifica",
    badge: "Attivo",
    icon: "MS",
    status: "attivo",
    accepts: ["pdf"],
    description: "Riduce il contenuto su ogni pagina lasciando un bordo sicuro per la stampa.",
    options: [
      {
        id: "scale",
        label: "Riduzione",
        type: "select",
        value: "0.94",
        choices: [
          ["0.97", "Leggera"],
          ["0.94", "Media"],
          ["0.90", "Forte"],
        ],
      },
    ],
  },
  {
    id: "crop-marks",
    name: "Segni di taglio",
    category: "Modifica",
    badge: "Attivo",
    icon: "✂",
    status: "attivo",
    accepts: ["pdf"],
    description: "Aggiunge area esterna e crocini di taglio per stampa.",
    options: [
      {
        id: "slug",
        label: "Area esterna",
        type: "select",
        value: "24",
        choices: [
          ["18", "Compatta"],
          ["24", "Standard"],
          ["36", "Ampia"],
        ],
      },
    ],
  },
  {
    id: "add-blank-pages",
    name: "Aggiungi pagine vuote",
    category: "Modifica",
    badge: "Attivo",
    icon: "+",
    status: "attivo",
    accepts: ["pdf"],
    description: "Inserisce pagine vuote all'inizio o alla fine del PDF.",
    options: [
      { id: "count", label: "Numero pagine", type: "text", value: "1", hint: "Esempio: 2" },
      {
        id: "position",
        label: "Posizione",
        type: "select",
        value: "end",
        choices: [
          ["end", "Alla fine"],
          ["start", "All'inizio"],
        ],
      },
    ],
  },
  {
    id: "crop-margins",
    name: "Ritaglia margini",
    category: "Modifica",
    badge: "Attivo",
    icon: "C",
    status: "attivo",
    accepts: ["pdf"],
    description: "Applica un crop box interno per nascondere bordi o margini.",
    options: [
      {
        id: "crop",
        label: "Ritaglio",
        type: "select",
        value: "24",
        choices: [
          ["12", "Leggero"],
          ["24", "Medio"],
          ["48", "Forte"],
        ],
      },
    ],
  },
  {
    id: "auto-trim",
    name: "Auto ritaglia bianco",
    category: "Modifica",
    badge: "Attivo",
    icon: "T",
    status: "attivo",
    accepts: ["pdf"],
    description: "Rileva contenuto visibile e imposta crop box per ridurre margini bianchi.",
    options: [
      {
        id: "padding",
        label: "Respiro",
        type: "select",
        value: "12",
        choices: [
          ["6", "Minimo"],
          ["12", "Medio"],
          ["24", "Ampio"],
        ],
      },
    ],
  },
  {
    id: "normalize-size",
    name: "Normalizza formato",
    category: "Modifica",
    badge: "Attivo",
    icon: "A4",
    status: "attivo",
    accepts: ["pdf"],
    description: "Ricrea le pagine in A4 verticale/orizzontale mantenendo proporzioni.",
    options: [
      {
        id: "pageSize",
        label: "Formato",
        type: "select",
        value: "a4-portrait",
        choices: [
          ["a4-portrait", "A4 verticale"],
          ["a4-landscape", "A4 orizzontale"],
          ["letter-portrait", "Letter verticale"],
          ["letter-landscape", "Letter orizzontale"],
        ],
      },
    ],
  },
  {
    id: "flatten-forms",
    name: "Appiattisci moduli",
    category: "Modifica",
    badge: "Attivo",
    icon: "F",
    status: "attivo",
    accepts: ["pdf"],
    description: "Rende statici i campi modulo compilati.",
  },
  {
    id: "metadata",
    name: "Leggi metadati",
    category: "Privacy",
    badge: "Attivo",
    icon: "M",
    status: "attivo",
    accepts: ["pdf"],
    description: "Genera un report TXT con metadati e numero pagine.",
  },
  {
    id: "set-metadata",
    name: "Scrivi metadati",
    category: "Privacy",
    badge: "Attivo",
    icon: "WM",
    status: "attivo",
    accepts: ["pdf"],
    description: "Imposta titolo, autore, oggetto e keyword senza caricare file.",
    options: [
      { id: "title", label: "Titolo", type: "text", value: "Documento PdfDelta", hint: "Titolo documento" },
      { id: "author", label: "Autore", type: "text", value: "PdfDelta", hint: "Autore" },
      { id: "subject", label: "Oggetto", type: "text", value: "PDF gratuito", hint: "Oggetto" },
      { id: "keywords", label: "Keyword", type: "text", value: "pdf,free,local", hint: "Separate da virgola" },
    ],
  },
  {
    id: "clean-metadata",
    name: "Pulisci metadati",
    category: "Privacy",
    badge: "Attivo",
    icon: "Z",
    status: "attivo",
    accepts: ["pdf"],
    description: "Rimuove o neutralizza i metadati principali del documento.",
  },
  {
    id: "remove-annotations",
    name: "Rimuovi annotazioni",
    category: "Privacy",
    badge: "Attivo",
    icon: "A",
    status: "attivo",
    accepts: ["pdf"],
    description: "Elimina link, commenti e annotazioni pagina dal PDF.",
  },
  {
    id: "clean-actions",
    name: "Pulisci azioni",
    category: "Privacy",
    badge: "Attivo",
    icon: "JS",
    status: "attivo",
    accepts: ["pdf"],
    description: "Rimuove apertura automatica, azioni pagina e JavaScript incorporato.",
  },
  {
    id: "attachments-report",
    name: "Report allegati",
    category: "Privacy",
    badge: "Attivo",
    icon: "AL",
    status: "attivo",
    accepts: ["pdf"],
    description: "Elenca gli allegati incorporati rilevati nel PDF.",
  },
  {
    id: "remove-attachments",
    name: "Rimuovi allegati",
    category: "Privacy",
    badge: "Attivo",
    icon: "X",
    status: "attivo",
    accepts: ["pdf"],
    description: "Rimuove allegati e file associati dal catalogo PDF quando presenti.",
  },
  {
    id: "attach-files",
    name: "Allega file a PDF",
    category: "Privacy",
    badge: "Nuovo",
    icon: "AF",
    status: "attivo",
    minFiles: 2,
    accepts: ["pdf", "jpg", "jpeg", "png", "txt"],
    description: "Aggiunge immagini, TXT o altri PDF come allegati incorporati al primo PDF.",
  },
  {
    id: "sanitize-raster",
    name: "Sanitizza raster",
    category: "Privacy",
    badge: "Attivo",
    icon: "S",
    status: "attivo",
    accepts: ["pdf"],
    description: "Renderizza e ricrea il PDF come immagini, rimuovendo livelli, form e metadati nascosti.",
    options: [
      {
        id: "scale",
        label: "Qualità",
        type: "select",
        value: "1.25",
        choices: [
          ["1", "Standard"],
          ["1.25", "Alta"],
          ["1.75", "Massima"],
        ],
      },
    ],
  },
  {
    id: "grayscale-raster",
    name: "Scala di grigi",
    category: "Ottimizza",
    badge: "Attivo",
    icon: "G",
    status: "attivo",
    accepts: ["pdf"],
    description: "Renderizza e ricrea il PDF in scala di grigi, utile per stampa e allegati leggeri.",
    options: [
      {
        id: "scale",
        label: "Qualità",
        type: "select",
        value: "1.25",
        choices: [
          ["1", "Standard"],
          ["1.25", "Alta"],
          ["1.75", "Massima"],
        ],
      },
    ],
  },
  {
    id: "protect",
    name: "Proteggi PDF",
    category: "Privacy",
    badge: "Bloccato",
    icon: "P",
    status: "bloccato",
    accepts: ["pdf"],
    description: "La cifratura PDF robusta non è supportata da pdf-lib in browser.",
  },
  {
    id: "unlock",
    name: "Sblocca PDF",
    category: "Privacy",
    badge: "Bloccato",
    icon: "U",
    status: "bloccato",
    accepts: ["pdf"],
    description: "Rimuovere protezioni richiede strumenti server e controlli legali.",
  },
  {
    id: "redact",
    name: "Censura sicura",
    category: "Privacy",
    badge: "Bloccato",
    icon: "C",
    status: "bloccato",
    accepts: ["pdf"],
    description: "La redazione vera deve rimuovere contenuto, non coprirlo. Bloccata per sicurezza.",
  },
  {
    id: "compare-text",
    name: "Confronta testo",
    category: "Analisi",
    badge: "Attivo",
    icon: "Δ",
    status: "attivo",
    minFiles: 2,
    maxFiles: 2,
    accepts: ["pdf"],
    description: "Confronta il testo estratto da due PDF e genera un report HTML.",
  },
  {
    id: "compare-visual",
    name: "Confronta visuale",
    category: "Analisi",
    badge: "Attivo",
    icon: "V",
    status: "attivo",
    minFiles: 2,
    maxFiles: 2,
    accepts: ["pdf"],
    description: "Confronta le pagine renderizzate e segnala differenze visive in HTML.",
    options: [
      {
        id: "sensitivity",
        label: "Sensibilità",
        type: "select",
        value: "32",
        choices: [
          ["18", "Alta"],
          ["32", "Media"],
          ["54", "Bassa"],
        ],
      },
    ],
  },
  {
    id: "audit",
    name: "Audit accessibilità",
    category: "Analisi",
    badge: "Parziale",
    icon: "A",
    status: "parziale",
    accepts: ["pdf"],
    description: "Controlla testo estraibile, numero pagine e metadati base.",
  },
  {
    id: "word-count",
    name: "Conta parole",
    category: "Analisi",
    badge: "Nuovo",
    icon: "123",
    status: "attivo",
    accepts: ["pdf"],
    description: "Genera un CSV con pagine, parole e caratteri del testo estraibile.",
  },
  {
    id: "document-report",
    name: "Report documento",
    category: "Analisi",
    badge: "Nuovo",
    icon: "CSV",
    status: "attivo",
    accepts: ["pdf"],
    description: "Esporta un CSV con pagine, dimensioni, orientamento e metadati dei PDF.",
  },
  {
    id: "queue-report",
    name: "Report coda",
    category: "Analisi",
    badge: "Nuovo",
    icon: "RQ",
    status: "attivo",
    accepts: ["pdf", "jpg", "jpeg", "png", "txt"],
    description: "Scarica un CSV con nome, tipo e peso dei file caricati nella pipeline.",
  },
  {
    id: "extract-by-text",
    name: "Estrai per testo",
    category: "Analisi",
    badge: "Attivo",
    icon: "T+",
    status: "attivo",
    accepts: ["pdf"],
    description: "Crea un PDF con le pagine che contengono una parola o frase.",
    options: [{ id: "query", label: "Testo da cercare", type: "text", value: "PdfDelta", hint: "Ricerca non sensibile a maiuscole" }],
  },
  {
    id: "remove-by-text",
    name: "Rimuovi per testo",
    category: "Analisi",
    badge: "Attivo",
    icon: "T-",
    status: "attivo",
    accepts: ["pdf"],
    description: "Crea una copia senza le pagine che contengono una parola o frase.",
    options: [{ id: "query", label: "Testo da cercare", type: "text", value: "PdfDelta", hint: "Ricerca non sensibile a maiuscole" }],
  },
  {
    id: "split-by-text",
    name: "Dividi per testo",
    category: "Analisi",
    badge: "Attivo",
    icon: "T/",
    status: "attivo",
    accepts: ["pdf"],
    description: "Divide il PDF quando una pagina contiene una parola o frase marker.",
    options: [{ id: "query", label: "Marker", type: "text", value: "Fattura", hint: "Ogni pagina marker apre un nuovo blocco" }],
  },
  {
    id: "remove-blank-pages",
    name: "Rimuovi pagine bianche",
    category: "Analisi",
    badge: "Attivo",
    icon: "B",
    status: "attivo",
    accepts: ["pdf"],
    description: "Rileva pagine quasi vuote e crea una copia senza quelle pagine.",
    options: [
      {
        id: "threshold",
        label: "Sensibilità",
        type: "select",
        value: "0.003",
        choices: [
          ["0.001", "Alta"],
          ["0.003", "Media"],
          ["0.008", "Bassa"],
        ],
      },
    ],
  },
  {
    id: "split-blank-pages",
    name: "Dividi su pagine bianche",
    category: "Analisi",
    badge: "Attivo",
    icon: "B/",
    status: "attivo",
    accepts: ["pdf"],
    description: "Usa le pagine bianche come separatori e genera uno ZIP di blocchi.",
    options: [
      {
        id: "threshold",
        label: "Sensibilità",
        type: "select",
        value: "0.003",
        choices: [
          ["0.001", "Alta"],
          ["0.003", "Media"],
          ["0.008", "Bassa"],
        ],
      },
    ],
  },
  {
    id: "split-orientation",
    name: "Separa orientamento",
    category: "Analisi",
    badge: "Attivo",
    icon: "O",
    status: "attivo",
    accepts: ["pdf"],
    description: "Divide pagine verticali e orizzontali in PDF separati dentro uno ZIP.",
  },
  {
    id: "page-size-report",
    name: "Report formati pagina",
    category: "Analisi",
    badge: "Attivo",
    icon: "MM",
    status: "attivo",
    accepts: ["pdf"],
    description: "Esporta un CSV con formato, dimensioni e orientamento di ogni pagina.",
  },
  {
    id: "split-by-size",
    name: "Separa per formato",
    category: "Analisi",
    badge: "Attivo",
    icon: "F",
    status: "attivo",
    accepts: ["pdf"],
    description: "Divide un PDF misto in file separati per formato e orientamento pagina.",
  },
  {
    id: "remove-duplicates",
    name: "Rimuovi duplicati",
    category: "Analisi",
    badge: "Attivo",
    icon: "2",
    status: "attivo",
    accepts: ["pdf"],
    description: "Rileva pagine visualmente identiche e tiene solo la prima occorrenza.",
  },
  {
    id: "ocr",
    name: "OCR PDF",
    category: "AI",
    badge: "Roadmap",
    icon: "O",
    status: "bloccato",
    description: "OCR locale possibile ma pesante. Lo terremo opzionale per non degradare il free hosting.",
  },
  {
    id: "summarize",
    name: "Riassumi PDF",
    category: "AI",
    badge: "Bloccato",
    icon: "R",
    status: "bloccato",
    description: "AI senza API pagate: bloccato finche il progetto deve costare zero.",
  },
  {
    id: "translate",
    name: "Traduci PDF",
    category: "AI",
    badge: "Bloccato",
    icon: "T",
    status: "bloccato",
    description: "Traduzione affidabile richiede modelli/API con costo o hosting compute.",
  },
  {
    id: "chat",
    name: "Chat con PDF",
    category: "AI",
    badge: "Bloccato",
    icon: "Q",
    status: "bloccato",
    description: "RAG e LLM richiedono compute/API. Non compatibile con zero costi nascosti.",
  },
];

